sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/gcloud/
env:
- GOOGLE_APPLICATION_CREDENTIALS=$HOME/paxportcloud-travis-ci.json
before_install:
- openssl aes-256-cbc -K $encrypted_7bc56c2fd7ac_key -iv $encrypted_7bc56c2fd7ac_iv
  -in paxportcloud-travis-ci.json.enc -out $GOOGLE_APPLICATION_CREDENTIALS -d
- if [ ! -d $HOME/google-cloud-sdk ]; then curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-135.0.0-linux-x86_64.tar.gz
  -o gcloudsdk.tar.gz; tar -xvzf gcloudsdk.tar.gz; ./google-cloud-sdk/install.sh --quiet;
  fi
- ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
